### PR TITLE
Fixed Bug where as CT would spit out 'Terrorists are ready, waiting f…

### PR DESCRIPTION
**Pull request by dejavueakay**
…or Counter-Terrorists...'. It is not as cleanly fixed as i'd have liked it but its a temporary fix until we can find a better solution.

### CODE REVIEW

**Comment by JamesCullum** [comment]
Thank you for helping the tool improve!

Can you give me some background of the bug?
Have you debugged the cause of it and can provide the exact value of all variables involved?
The code looks exactly the same, apart from the strict validation.

**Comment by dejavueakay** [comment]
Hey there!

I honestly didn't expect you'd be interested / still keeping the repo up to date! Thank you for your V2 version :) I'm sorry, I'd have done a detailed answer if I'd known you would respond.

Here you go:

** Brief Description:** While match state is paused when writing !ready as Counter-Terrorist the bot answers with "Terrorists are !ready, waiting for Counter-Terrorists."

**Steps to reproduce:**

- Start a match
- Call a !pause on any site
- Call !unpause as Counter-Terrorist
- Bot answers with "Terrorists are !ready, waiting for Counter-Terrorists."

**Expected result:** Expected answer of bot is "Counter-Terrorists are !ready, waiting for Terrorists."


**Code Background:**

Involved variables: this.state.unpause.TERRORIST, this.state.unpause.CT - Both of them work correctly and get the correct value. The variables this.state.ready.TEAM have not been checked.

Suspected problem: Condition on line 548 is not working properly. The Condition always answers with "T : CT", whereas it should answer "CT : T" when Counter-Terrorists call !ready (this.state.unpause.CT === true).

Temporary fix was to rewrite the condition into a if else statement since im not familiar with that specific type of condition formatting and also using the variables this.state.unpause.TEAM instead of this.state.ready.TEAM.

Problems with the fix: The fix hardcodes the bot answers instead of calling the template READY from line 22. Will look into using the template.

**Comment by dejavueakay** [comment]
I found a better solution to the problem. It seems like the variables this.state.ready.TEAM do not get the correct values or better said, do not represent the values that are needed for this condition. this.state.ready in the code is refered to the ready state of a team BEFORE starting the match instead of ready as in ready while match is paused.

The condition works as expected, we only have to change the variable this.state.ready.TERRORIST to this.state.unpause.TERRORIST which then gives the expected result:

line 548: this.rcon(READY.format(**this.state.unpause.TERRORIST** ? T : CT, **this.state.unpause.TERRORIST** ? CT : T));

**Comment by JamesCullum** [comment]
I am active on GitHub, and as the original developer isn't anymore, I will do my best to give a viable alternative :+1: 

Thank you for your commits and taking the time to debug it. As imagined, the difference is quite small, as the code basically did very similiar things.

Can you give me a bit of background regarding your V3? If you want to I can just make you a maintainer of this project and you update it here. I think it is beneficial if we don't open too many projects that are in different steps of development of the same tool, so that users can find it more easily.

**Comment by dejavueakay** [comment]
Hey :)

Thank you for asking! Unfortunately I'm looking into adding alot more functionalities on the fly which is easier to do with an own fork, also since we are 3 people currently working on it. But I do see your point, it would've been easier. If the versioning bothers you I'll change it. I hope it doesn't bother you too much. You're always welcome to take over any code you wish and like :) If you want you can leave the pull request open to stay informed on further commits, but be ready for alot of notifications.

Thank you for your answer and have a nice day!

**Comment by JamesCullum** [comment]
Sure, very understandeable!

My idea is just that it isn't actually 3 people working on it. The original repository is not maintained and I don't develop the code anymore because my use cases are done. The only person actively developing you would be you.

Now if you have your own code as V3 (the number doesn't matter tbh), we have 3 repositories as well, organized by different people. One is the very oudated first version, then comes mine and then yours. As those version numbers are completely arbitrary, it is not easy for users to understand, where to start and which one to trust.

This is why I think it would make sense that your V3 overrides my V2, and if you become inactive and someone goes for a V4, that goes here as well. You're free to run your own fork of course, it's just to make it more maintainable.

**Pull request closed without merging**
